name: Main
on: [ push, pull_request, workflow_dispatch ]
jobs:
# ---------------------------------- Lint ----------------------------------
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: yarn

    - name: Run ESLint
      run: yarn lint
# ------------------------------ Build Project -----------------------------
  build_project:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2

    - name: Build project files
      run: yarn build
# ------------------------------ Build Docker ------------------------------
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build . -t ci:0
  
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v3
      with:
        webhook_url: ${{ secrets.WEBHOOK_URL }}